version: '3.1'

services:
  mongo:
    image: mongo
    container_name: post-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha123

volumes:
  mongodb_data:
    driver: local