version: '3.1'

services:
  post-mongo:
    image: mongo
    container_name: post-mongo
    ports:
      - "27017:27017"
    volumes:
      - post_mongodb:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha123
  
  profile-mongo:
    image: mongo
    container_name: profile-mongo
    ports:
      - "27018:27017"
    volumes:
      - profile_mongodb:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha123

volumes:
  post_mongodb:
    driver: local
  profile_mongodb:
    driver: local